set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -g mouse on
set -g prefix C-a
set -g allow-passthrough all
set-option -sg escape-time 10
set-option -g focus-events on

# Vim-like key binding
set -g mode-keys vi

set -g @continuum-boot 'on'
set -g @continuum-boot-options 'iterm'
set -g @continuum-restore 'on'

set -g @tmux_power_theme '#58A6FF'
set -g @tmux_power_show_user false
set -g @tmux_power_show_host false

run-shell ~/.config/tmux/plugins/tmux-power/tmux-power.tmux
run-shell ~/.config/tmux/plugins/tmux-smooth-scroll/smooth-scroll.tmux
run-shell ~/.config/tmux/plugins/tmux-sensible/sensible.tmux
run-shell ~/.config/tmux/plugins/tmux-resurrect/resurrect.tmux
